= Лабораторна робота №6

== Тема: Розробка програм з використання рядкового типу даних

Мета роботи: оволодіння навичками складання програм з використанням рядкового типу даних за допомогою засобів мови Kotlin.

== Завдання 6.1 Скласти програму для виконання наступних дій і виконати її в середовищі програмування.
_У всіх завданнях вважати, що рядок може містити лише літери, цифри та знаки пробілу. Слово - послідовність символів, що не містить пробілів._

=== Варіанти 1-3
Визначення кількості слів у рядку

=== Варіанти 4-6
Вилучення усіх цифр в рядку

=== Варіанти 7-9
Інвертування символів у рядку

=== Варіанти 10-12
Визначення кількості цифр у рядку

=== Варіанти 13-15
Визначення слова з найменшою кількістю літер в рядку

=== Варіанти 16-18
Визначення кількості чисел у рядку

=== Варіанти 19-21
 Визначення слова з найбільшою кількістю літер у рядку

=== Варіанти 22-24
Заміна усіх великих букв в рядку на малі

=== Варіанти 25-27
Вилучення зайвих символів «пробіл» в рядку

=== Варіанти 28-30
Заміна усіх малих букв в рядку на великі


